import {test,expect} from '@playwright/test';
import {inflateRawSync} from 'node:zlib';
function part(bytes,path){const b=Buffer.from(bytes);for(let i=0;i<b.length-46;i++){if(b.readUInt32LE(i)!==0x02014b50)continue;const n=b.readUInt16LE(i+28),name=b.subarray(i+46,i+46+n).toString();if(name!==path)continue;const start=b.readUInt32LE(i+42),data=start+30+b.readUInt16LE(start+26)+b.readUInt16LE(start+28),compressed=b.subarray(data,data+b.readUInt32LE(i+20));return (b.readUInt16LE(i+10)===8?inflateRawSync(compressed):compressed).toString();}throw Error('Missing DOCX part '+path);}
async function ready(page){await page.goto('/radar.html');await page.waitForFunction(()=>!!window.ProyectaExport&&!!window.ProyectaPreview);}
test('three professional presentations create valid PDFs and editable Word with matching fonts and margins',async({page})=>{
 await ready(page);const result=await page.evaluate(async()=>{const blocks=[{text:'Dossier profesional',style:'title'},{text:'OBJETIVOS',style:'heading'},{text:'Una propuesta clara con experiencia contrastada. '.repeat(60),style:'body'}];const out=[];for(const layout of ['classic','editorial','compact']){const pdf=await ProyectaExport.pdf(blocks,{layout}),parsed=await PDFLib.PDFDocument.load(await pdf.arrayBuffer()),word=await ProyectaExport.word(blocks,{layout});out.push({layout,subject:parsed.getSubject(),pages:parsed.getPageCount(),word:Array.from(new Uint8Array(await word.arrayBuffer()))});}return out;});
 const expected={classic:{label:'Clásico',font:'Arial',margin:1080},editorial:{label:'Editorial',font:'Times New Roman',margin:1160},compact:{label:'Compacto',font:'Arial',margin:800}};
 for(const r of result){expect(r.subject).toContain(expected[r.layout].label);expect(r.pages).toBeGreaterThan(0);const xml=part(r.word,'word/document.xml');expect(xml).toContain('w:ascii="'+expected[r.layout].font+'"');expect(xml).toContain('w:top="'+expected[r.layout].margin+'"');expect(xml).toContain('Dossier profesional');}
});
test('export presentation follows preview selection and PDF download matches the selected rendered file',async({page})=>{
 await ready(page);await page.evaluate(()=>{Object.defineProperty(navigator,'pdfViewerEnabled',{value:true,configurable:true});window.ProyectaDownload=async(blob,name)=>{window.savedLayout={name,bytes:Array.from(new Uint8Array(await blob.arrayBuffer()))};};ProyectaExport.choose('Dossier',[{text:'Mi proyecto',style:'title'},{text:'Descripción',style:'body'}]);});
 await page.locator('.export-dialog [name=layout]').selectOption('editorial');await page.locator('.export-dialog [data-preview]').click();await expect(page.locator('.document-preview')).toHaveAttribute('data-preview-layout','editorial');await page.locator('.document-preview select').selectOption('compact');await expect(page.locator('.document-preview')).toHaveAttribute('data-preview-layout','compact');const bytes=await page.locator('.preview-pdf').evaluate(async frame=>Array.from(new Uint8Array(await(await fetch(frame.src.split('#')[0])).arrayBuffer())));await page.getByRole('button',{name:'Descargar PDF',exact:true}).click();await expect.poll(()=>page.evaluate(()=>window.savedLayout?.bytes)).toEqual(bytes);await page.getByRole('button',{name:'Volver al documento'}).click();await expect(page.locator('.export-dialog [name=layout]')).toHaveValue('compact');
});
test('slow previous PDF generation cannot replace the latest selected presentation',async({page})=>{
 await ready(page);await page.evaluate(()=>{const build=ProyectaExport.buildPdf;ProyectaExport.buildPdf=async(blocks,options)=>{const blob=await build(blocks,options);if(options.layout==='classic')await new Promise(resolve=>setTimeout(resolve,250));return blob;};ProyectaPreview('Prueba',[{text:'Contenido',style:'body'}]);});await page.locator('.document-preview select').selectOption('editorial');await page.locator('.document-preview select').selectOption('compact');await expect(page.locator('.document-preview')).toHaveAttribute('data-preview-layout','compact');await page.waitForTimeout(400);await expect(page.locator('.document-preview')).toHaveAttribute('data-preview-layout','compact');
});
